config/routes.rb
Contrac::Application.routes.draw do

  resources :people

  resources :tasks

  get "reports/select"
  post "reports/generate"
  get "reports/display"

  get "admin", :to => "admin#index"
  get "admin/notify"
  get "admin/scrape_news"
  get "admin/get_export"

  resources :companies
  resources :announcements

  resources :issues

  match "/login" => "sessions#new", :as => :login
  match "/logout" => "sessions#destroy", :as => :logout

  resources :sessions, :only => [:new, :create, :destroy]

  resources :users do
    collection do
      post 'become'
    end
  end

  resources :comments
  resources :tasks do
    member do
      delete 'cancel'
    end
  end
  resources :settings

  match "/about" => "pages#about"
  match "/help" => 'pages#help'
  match "/contact" => 'pages#contact'
  match "/home" => 'pages#home'

  match "/delayed_job" => DelayedJobWeb, :anchor => false

#  match "/users" => 'user#index'

  resources :opportunities do
    collection do
      post 'filter','calendar_order_by'
      get 'my', 'calendar', 'all', 'dashboard','export'
    end
    member do
      post 'watch', 'own'
    end
    resources :comments
    resources :tasks
  end

  resources :input_records, :only => [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'import'
      post 'upload'
      put 'merge'
    end
  end

  root :to => "pages#home"

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  before_save :format
  
  validates_presence_of :author, :content, :title
  
  def self.for_front_page(limit = 3)
    limit(limit).where("updated_at > ?",14.days.ago).order("updated_at desc")
  end
  
  
  private
    def format
      self.formatted_text = RedCloth.new(self.content,[:sanitize_html]).to_html
    end
    
end

# == Schema Information
#
# Table name: announcements
#
#  id             :integer         primary key
#  author         :string(255)
#  content        :text
#  created_at     :timestamp
#  updated_at     :timestamp
#  title          :string(255)
#  formatted_text :text
#

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  
  #before_filter :require_login
  
  # GET /announcements
  # GET /announcements.xml
  def index
    @announcements = Announcement.order("updated_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new
    @announcement.author = current_user.name  # set default

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully created.') }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= simple_form_for(@announcement) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
		<%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :author %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Announcements</h1>

<table>
	<thead>
  <tr>
		<th>Title</th>
    <th>Content</th>
    <th>Author</th>
    <th></th>
  </tr>
	</thead>
	<tbody>
<% @announcements.each do |announcement| %>
  <tr>
		<td><%= announcement.title %><br/>
				<%= announcement.updated_at%></td>
    <td><%= announcement.formatted_text.html_safe %></td>
    <td><%= announcement.author %></td>
    <td><%= link_to 'Show', announcement %><br/>
    		<%= link_to 'Edit', edit_announcement_path(announcement) %><br/>
    		<%= link_to 'Destroy', announcement, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
	</tbody>
</table>

<br />

<%= button_to 'New Announcement', new_announcement_path, :method => :get %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @announcement.author %>
</p>

<p>
  <b>Content:</b>
  <%= @announcement.content %>
</p>

<p>
  <b>Formatted Text:</b>
  <%= @announcement.formatted_text.html_safe %>
</p>



<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>