config/routes.rb
Contrac::Application.routes.draw do

  resources :people

  resources :tasks

  get "reports/select"
  post "reports/generate"
  get "reports/display"

  get "admin", :to => "admin#index"
  get "admin/notify"
  get "admin/scrape_news"
  get "admin/get_export"

  resources :companies
  resources :announcements

  resources :issues

  match "/login" => "sessions#new", :as => :login
  match "/logout" => "sessions#destroy", :as => :logout

  resources :sessions, :only => [:new, :create, :destroy]

  resources :users do
    collection do
      post 'become'
    end
  end

  resources :comments
  resources :tasks do
    member do
      delete 'cancel'
    end
  end
  resources :settings

  match "/about" => "pages#about"
  match "/help" => 'pages#help'
  match "/contact" => 'pages#contact'
  match "/home" => 'pages#home'

  match "/delayed_job" => DelayedJobWeb, :anchor => false

#  match "/users" => 'user#index'

  resources :opportunities do
    collection do
      post 'filter','calendar_order_by'
      get 'my', 'calendar', 'all', 'dashboard','export'
    end
    member do
      post 'watch', 'own'
    end
    resources :comments
    resources :tasks
  end

  resources :input_records, :only => [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'import'
      post 'upload'
      put 'merge'
    end
  end

  root :to => "pages#home"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  belongs_to :opportunity
  belongs_to :assigned_by, class_name: "User"

  attr_accessible :name, :notes, :owner_id, :opportunity_id, :status, :due_date, :status_date, :status_notes, :assigned_by_id

  STATUSES = %w[Open Closed Cancelled]

  validates_presence_of :name

  scope :status_open,
    where("status is null or status = 'Open'")

  scope :status_closed,
    where("status = 'Closed'")

  scope :status_cancelled,
    where("status = 'Cancelled'")

  scope :due_before,
    lambda { |time| where("due_date is null or due_date < ?",time)}

  def self.mine(who)
    where("owner_id = ?",who.id)
  end

  def self.my_upcoming(who)
    status_open.mine(who).due_before(7.days.from_now)
  end

end



# == Schema Information
#
# Table name: tasks
#
#  id             :integer         not null, primary key
#  name           :string(255)
#  notes          :text
#  owner_id       :integer
#  opportunity_id :integer
#  status         :string(255)
#  assigned_by_id :integer
#  created_at     :datetime
#  updated_at     :datetime
#  due_date       :date
#  status_date    :date
#  status_notes   :text
#

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :require_login

  # GET /tasks
  # GET /tasks.json
  def index
    #@tasks = Task.all
    if current_user.admin?
      @open_tasks = Task.status_open.order("due_date")
      @closed_tasks = Task.status_closed.order("due_date")
    else
      @open_tasks = Task.mine(current_user).status_open.order("due_date")
      @closed_tasks = Task.mine(current_user).status_closed.order("due_date")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new

    @task = Task.new
    @task.opportunity_id = params[:opportunity_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
      format.js
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @saved = @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    @newtask = @task.opportunity.tasks.build()

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
      format.js
    end
  end

  # DELETE /tasks/1/cancel
  # DELETE /tasks/1.json
  def cancel
    @task = Task.find(params[:id])
    @task.status = "Cancelled"
    @task.status_date = Date.today
    @task.save

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
      format.js
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_status_class(status)
    case status
    when "Open"
      "success"
    when "Closed"
      "notice"
    when "Cancelled"
      ""
    end
  end

  def get_upcoming_tasks
    @upcoming_tasks = Task.my_upcoming(current_user).limit(7)
  end

  def task_header(t)
    if t.new_record?
      "New Task"
    else
      ((t.opportunity.acronym.blank? ? t.opportunity.program : t.opportunity.acronym)  + " [" + link_to('Go', t.opportunity) +"]").html_safe
    end
  end
end

app/views/tasks/_form.html.erb
<%= simple_form_for @task, remote: true do |form| %>
<div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <%= content_tag(:h3, task_header(@task)) %>
</div>
<div class="modal-body">
    <%= form.input :name, label: "Task Name" %>
    <%= form.input :notes, input_html: {rows: 3}%>
    <%= form.association :owner %>
    <%= form.input :due_date, as: :string, input_html: {name: "task[due_date]", type: "date"} %>
    <%= form.input :status, as: :select, collection: Task::STATUSES %>
    <%= form.input :status_date, as: :string, input_html: {name: "task[status_date]", type: "date"} %>
    <%= form.input :status_notes, input_html: {rows: 3} %>
    <%= form.input :opportunity_id, as: :hidden, value: @task.opportunity_id %>
    <%= form.input :assigned_by, value: "#{current_user.id}" , as: :hidden %>
</div>
<div class="modal-footer">
    <%= form.button :submit, class: "btn btn-primary" %>
</div>
<% end %>

app/views/tasks/_task.html.erb
<li id="task-<%= task.id %>"><%= content_tag(:h3, content_tag(:span, task.status, class: "label #{task_status_class(task.status)}") + " " + task.name )%>
<%= task.notes %><br/>
Assigned to: <%= task.owner.nil? ? "Unassigned" : task.owner.name %></br>
Due: <%= task.due_date %><br/>
<%= link_to "Edit", edit_task_path(task), remote: true %> | <%= link_to 'Cancel', cancel_task_path(task), confirm: 'Are you sure?', method: :delete, remote: true %> | <%= link_to 'Delete', task, confirm: 'Are you sure?', method: :delete, remote: true %>
</li>

app/views/tasks/_tasks.html.erb
<h3>Tasks</h3>
<%= link_to "New Task", new_opportunity_task_path(f), remote: true, class: "btn btn-primary btn-small" %>

<ul id="tasks">
  <% f.tasks.each do |task| %>
    <%= render "tasks/task", task: task if task.id %>
  <% end %>
</ul>

app/views/tasks/cancel.js.erb
$("#task-<%= @task.id %>").html('<%= j render("tasks/task", task: @task ) %>');

app/views/tasks/create.js.erb
<% if @saved %>
$("#tasks").prepend('<%= j render("tasks/task", task: @task) %>');
$("#tasks-form").modal('hide');
<% else %>
alert("Task did not save");
<% end %>

app/views/tasks/destroy.js.erb
$("#task-<%= @task.id %>").remove();

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$("#tasks-form").html('<%= j render("tasks/form") %>');
$("#tasks-form").modal("show");

app/views/tasks/index.html.erb
<h2>Open Tasks</h2>
<ul id="opentasks">
  <% @open_tasks.each do |task| %>
    <%= render "tasks/task", task: task if task.id %>
  <% end %>
</ul>

<h2>Closed Tasks</h2>
<ul id="closedtasks">
  <% @closed_tasks.each do |task| %>
    <%= render "tasks/task", task: task if task.id %>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$("#tasks-form").html('<%= j render("tasks/form") %>');
$("#tasks-form").modal("show");

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @task.notes %>
</p>

<p>
  <b>Owner:</b>
  <%= @task.owner %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Due at:</b>
  <%= @task.due_at %>
</p>

<p>
  <b>Closed at:</b>
  <%= @task.closed_at %>
</p>

<p>
  <b>Assigned by:</b>
  <%= @task.assigned_by %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$("#task-<%= @task.id %>").html('<%= j render("tasks/task", task: @task ) %>');
$("#tasks-form").modal("hide");
<% @task = @newtask %>
$("#tasks-form").html('<%= j render("tasks/form") %>');